---
version: '3.9'

services:
    frontend:
        image: 12-hello-frontend
        ports:
            - 5000:5000
        environment:
            REACT_APP_BACKEND_URL: http://localhost:8080
        command: bash -c "npm run build && serve -s -l 5000 build"
    
    backend:
        image: 13-hello-backend
        ports:
            - 8080:8080
        environment:
            REQUEST_ORIGIN: http://localhost:5000
            REDIS_HOST: redis
            POSTGRES_HOST: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres

    redis:
        image: redis
        restart: unless-stopped

    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres
        
