---
version: '3.9'

services:
    frontend:
        image: 12-hello-frontend
        environment:
            REACT_APP_BACKEND_URL: http://localhost:80
        command: bash -c "npm run build && serve -s -l 5000 build"
        container_name: frontend
    
    backend:
        image: 13-hello-backend
        environment:
            REQUEST_ORIGIN: http://localhost:80
            REDIS_HOST: redis
            POSTGRES_HOST: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        depends_on:
            - redis
            - db
        container_name: backend

    redis:
        image: redis
        restart: unless-stopped
        container_name: redis
        volumes:
            - ./redis_file:/data

    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres
        container_name: db_postgres
        volumes:
            - ./database:/var/lib/postgresql/data
    
    reverse-proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        container_name: reverse-proxy
        depends_on:
            - backend